# Generated by Django 6.1.1 on 2026-09-16 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_remove_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cosmetologist_verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата підтвердження косметолога'),
        ),
        migrations.AddField(
            model_name='user',
            name='cosmetologist_verified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cosmetologists', to=settings.AUTH_USER_MODEL, verbose_name='Хто підтвердив косметолога'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_cosmetologist_verified',
            field=models.BooleanField(default=False, help_text='Надає доступ до професійних цін і препаратів для спеціалістів.', verbose_name='Косметолога підтверджено'),
        ),
    ]
