# Generated by Django 6.1.1 on 2026-09-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage_recommendations',
            field=models.TextField(blank=True, verbose_name='Рекомендації щодо застосування'),
        ),
    ]
