# Generated by Django 6.1.1 on 2026-09-16 10:05

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "appointments",
            "0002_booking_client_name_booking_client_phone_and_more",
        ),
        ("crm", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ("-date", "-start_time"),
                "verbose_name": "Запис",
                "verbose_name_plural": "Записи",
            },
        ),
        migrations.AlterModelOptions(
            name="visitcomment",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Коментар до візиту",
                "verbose_name_plural": (
                    "Коментарі до візитів"
                ),
            },
        ),
        migrations.RenameField(
            model_name="visitcomment",
            old_name="text",
            new_name="comment",
        ),
        migrations.AddField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=(
                    django.db.models.deletion.SET_NULL
                ),
                related_name="bookings",
                to="crm.customer",
                verbose_name="Клієнт CRM",
            ),
        ),
        migrations.AddField(
            model_name="visitcomment",
            name="recommendations",
            field=models.TextField(
                blank=True,
                verbose_name="Рекомендації",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=(
                    django.db.models.deletion.SET_NULL
                ),
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обліковий запис клієнта",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="client_name",
            field=models.CharField(
                max_length=150,
                verbose_name="Ім’я клієнта",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="client_note",
            field=models.TextField(
                blank=True,
                verbose_name="Коментар клієнта",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="client_phone",
            field=models.CharField(
                max_length=30,
                verbose_name="Номер телефону",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name="Створено",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=(
                    django.db.models.deletion.SET_NULL
                ),
                related_name="created_bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Хто створив запис",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(
                verbose_name="Дата",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(
                editable=False,
                verbose_name="Час завершення",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="price_at_booking",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                max_digits=10,
                verbose_name="Ціна під час запису",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="procedure",
            field=models.ForeignKey(
                on_delete=(
                    django.db.models.deletion.PROTECT
                ),
                related_name="bookings",
                to="services.procedure",
                verbose_name="Процедура",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("online", "Сайт"),
                    ("admin", "Адміністратор"),
                    ("telegram", "Telegram"),
                ],
                default="online",
                max_length=20,
                verbose_name="Джерело",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.TimeField(
                verbose_name="Час початку",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        "pending",
                        "Очікує підтвердження",
                    ),
                    ("confirmed", "Підтверджено"),
                    ("completed", "Завершено"),
                    ("cancelled", "Скасовано"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                verbose_name="Оновлено",
            ),
        ),
        migrations.AlterField(
            model_name="visitcomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=(
                    django.db.models.deletion.SET_NULL
                ),
                related_name="authored_visit_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="visitcomment",
            name="booking",
            field=models.OneToOneField(
                on_delete=(
                    django.db.models.deletion.CASCADE
                ),
                related_name="visit_comment",
                to="appointments.booking",
                verbose_name="Запис",
            ),
        ),
        migrations.AlterField(
            model_name="visitcomment",
            name="comment",
            field=models.TextField(
                verbose_name="Коментар лікаря",
            ),
        ),
        migrations.AlterField(
            model_name="visitcomment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name="Створено",
            ),
        ),
        migrations.AlterField(
            model_name="visitcomment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                verbose_name="Оновлено",
            ),
        ),
    ]
