# Generated by Django 6.1.1 on 2026-09-16 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ім’я')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефону')),
                ('customer_type', models.CharField(choices=[('client', 'Звичайний клієнт'), ('cosmetologist', 'Косметолог')], default='client', max_length=20, verbose_name='Тип клієнта')),
                ('notes', models.TextField(blank=True, verbose_name='Внутрішні нотатки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('first_contact_at', models.DateTimeField(auto_now_add=True, verbose_name='Перше звернення')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Остання активність')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Обліковий запис')),
            ],
            options={
                'verbose_name': 'Клієнт CRM',
                'verbose_name_plural': 'Клієнти CRM',
                'ordering': ('-last_activity_at', 'full_name'),
            },
        ),
    ]
