# Generated by Django 6.1.1 on 2026-09-15 23:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('audience', 'start_date', 'title'), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курси'},
        ),
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'ordering': ('-enrolled_at',), 'verbose_name': 'Заявка на курс', 'verbose_name_plural': 'Заявки на курси'},
        ),
        migrations.RemoveConstraint(
            model_name='courseenrollment',
            name='unique_active_course_enrollment',
        ),
        migrations.AddField(
            model_name='course',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Для всіх'), ('cosmetologists', 'Для косметологів')], default='everyone', max_length=30, verbose_name='Для кого курс'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization_details',
            field=models.TextField(blank=True, default='Дата, час, формат, програма та остаточна вартість узгоджуються індивідуально після подання заявки.', verbose_name='Деталі організації навчання'),
        ),
        migrations.AddField(
            model_name='course',
            name='training_type',
            field=models.CharField(choices=[('individual', 'Індивідуальне'), ('group', 'Групове'), ('both', 'Індивідуальне або групове')], default='both', max_length=30, verbose_name='Тип навчання'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='applicant_comment',
            field=models.TextField(blank=True, verbose_name='Коментар або побажання'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ім’я заявника'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Тривалість у годинах'),
        ),
        migrations.AlterField(
            model_name='course',
            name='format',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн'), ('hybrid', 'Онлайн та офлайн')], default='online', max_length=20, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опублікований'),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Місце проведення'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Орієнтовна вартість'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Орієнтовна дата початку'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academy.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Хто створив'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подання заявки'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='price_at_enrollment',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Вартість на момент заявки'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='source',
            field=models.CharField(choices=[('online', 'Сайт'), ('clinic', 'Клініка'), ('telegram', 'Telegram')], default='online', max_length=20, verbose_name='Джерело'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Нова заявка'), ('contacted', 'Зв’язалися'), ('confirmed', 'Підтверджено'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Зареєстрований користувач'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('student', 'course'), name='unique_active_course_enrollment'),
        ),
    ]
