# Generated by Django 6.1.1 on 2026-09-16 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_course_options_alter_courseenrollment_options_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_applications', to='crm.customer', verbose_name='Клієнт CRM'),
        ),
    ]
